---
- name: Test if vault is unlocked
  ansible.builtin.command:
    cmd: bw status
  register: bw_status
  delegate_to: localhost
  run_once: true

- name: Assert vault is unlocked
  ansible.builtin.assert:
    that:
      - bw_status.stdout|from_json |json_query('status') == "unlocked"
    fail_msg: "Bitwarden vault is locked. Please unlock and run playbook again."
    success_msg: "Bitwarden vault is unlocked, continuing..."
  delegate_to: localhost
  run_once: true